- name: create mongodb repo setup
  ansible.buildin.file:
  src: mongo.repo
  dest: /etc/yum.repos.d/mongodb-org-8.0.repo
- name: install mongodb client
  ansible.builtin,package:
    name: mongodb-org-shell
    state: present
- name: start and enable mongodb
  ansible.builtin.service:
    name: mongodb
    state: start
    enable: yes
